return {
  'nvimtools/hydra.nvim',
  -- config = function()
  --   local Hydra = require 'hydra'
  --   Hydra {
  --     -- string? only used in auto-generated hint
  --     name = 'Treewalker',
  --
  --     -- string | string[] modes where the hydra exists, same as `vim.keymap.set()` accepts
  --     mode = { 'n', 'v' },
  --
  --     -- string? key required to activate the hydra, when excluded, you can use
  --     -- Hydra:activate()
  --     body = '<leader>w',
  --
  --     -- these are explained below
  --     hint = [[ Treewalker Hydra]],
  --     config = {
  --       foreign_keys = 'warn',
  --       color = 'red', -- "red" | "amaranth" | "teal" | "pink"
  --       invoke_on_body = true,
  --       hint = {
  --         position = 'bottom-right',
  --         offset = 5,
  --       },
  --     },
  --     heads = {
  --       -- Jump between nodes
  --       { 'j', '<cmd>Treewalker Down<cr>', { desc = 'Move down', nowait = true } },
  --       { 'k', '<cmd>Treewalker Up<cr>', { desc = 'Move up', nowait = true } },
  --       { 'h', '<cmd>Treewalker Left<cr>', { desc = 'Move out', nowait = true } },
  --       { 'l', '<cmd>Treewalker Right<cr>', { desc = 'Move in', nowait = true } },
  --       -- Actions on nodes
  --       { 'v', '<cmd>Treewalker Select<cr>', { desc = 'Select node', nowait = true } },
  --       -- Exit keys
  --       { 'q', nil, { exit = true, nowait = true, desc = 'exit' } },
  --       { '<esc>', nil, { exit = true, nowait = true, desc = 'exit' } },
  --     },
  --   }
  -- end,
}
